server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
 data:
    mongodb:
      uri: mongodb://192.168.1.10:27017
#      host: 127.0.0.1
#      prot: 27017
      database: xc_cms